% MATLAB script for Problem 38.2, Atkins and de Paula P-Chem Thermo

clear

% Data given in problem.  Cp in J/(mol K), T in K
Cpdata=[2.8,7.0,10.8,14.1,16.5,21.4,23.3,24.5,25.3,25.8,26.2,26.6];
Tdata=[10,15,20,25,30,50,70,100,150,200,250,298];

% Interesting to plot Cp by itself, then also Cp/T, the entropy integrand
% For the integrand, we manually add the data point for 0K, Cp/T -> 0
% In MATLAB, the . operator will make division do element by element
CpoverT=[0,Cpdata./Tdata];
% Also have to add to the xaxis (T)
T=[0,Tdata];

%  To create the figure, we can do it first manually/interactive, then
%  use the drop down menu to have it generate the code
%  Auto-generated by MATLAB on 22-Feb-2019 11:06:35
% Create figure
figure1 = figure;
% Comment out the line below if you want the figure to pop up
%set(figure1, 'Visible', 'off');
% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');
% Create plot
plot(T,CpoverT,'Marker','o');
% Create ylabel
ylabel({'Cp/T/(J/K)'});
% Create xlabel
xlabel({'T/K'});
title('Atkins Pr. 3B.2, Cp/T of Pb');
box(axes1,'on');

print('CpoverTplot.png','-dpng')

% Now, finally, after all that, we use the MATLAB trapezoidal integration
% routine to generate the output value.

Q=trapz(T,CpoverT);

disp('Estimated molar entropy of lead at 298 K, in J/(mol K):')
disp(Q)

